ARG ALPINE_VERSION=3.15
FROM alpine:${ALPINE_VERSION}

# Setup document root
WORKDIR /deployment

# Install packages and remove default server definition
RUN apk update && apk add --no-cache \
  curl \
  nginx \
  php7 \
  php7-ctype \
  php7-curl \
  php7-dom \
  php7-fpm \
  php7-gd \
  php7-intl \
  php7-json \
  php7-mbstring \
  php7-mysqli \
  php7-opcache \
  php7-openssl \
  php7-phar \
  php7-session \
  php7-xml \
  php7-xmlreader \
  php7-zlib \
  php7-memcached \
  php7.4-redis \
  php7.4-sqlite3 \
  php7.4-bz2 php7.4-mongodb php7.4-tidy php7.4-yaml \
  php7.4-pgsql \
  php7.4-mysql \
  php7.4-common \
  php7.4-soap \
  php7.4-cli \
  php7.4-xsl \
  php7.4-imap \
  php7.4-ldap \
  php7.4-dev \
  php7.4-bcmath \
  php7.4-zip \
  supervisor

# Configure nginx
COPY config/nginx.conf /etc/nginx/nginx.conf

# Configure PHP-FPM
COPY config/fpm-pool.conf /etc/php7/php-fpm.d/www.conf
COPY config/php.ini /etc/php7/conf.d/custom.ini

# Configure supervisord
COPY config/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Make sure files/folders needed by the processes are accessable when they run under the nobody user
RUN chown -R nobody.nobody /deployment /run /var/lib/nginx /var/log/nginx

# Switch to use a non-root user from here on
USER nobody

# Expose the port nginx is reachable on
EXPOSE 8080

# Let supervisord start nginx & php-fpm
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]

# Configure a healthcheck to validate that everything is up&running
HEALTHCHECK --timeout=10s CMD curl --silent --fail http://127.0.0.1:8080/fpm-ping
